//posts
export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS';
export const POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR';

//activePost
export const ACTIVE_POST_REQUEST = 'ACTIVE_POST_REQUEST';
export const ACTIVE_POST_REQUEST_SUCCESS = 'ACTIVE_POST_REQUEST_SUCCESS';
export const ACTIVE_POST_REQUEST_ERROR = 'ACTIVE_POST_REQUEST_ERROR';

//users
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS';
export const USERS_REQUEST_ERROR = 'USERS_REQUEST_ERROR';

//users
export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS';
export const COMMENTS_REQUEST_ERROR = 'COMMENTS_REQUEST_ERROR';

//search
export const  SEARCH_REQUEST = ' SEARCH_REQUEST';
export const  SEARCH_REQUEST_SUCCESS = ' SEARCH_REQUEST_SUCCESS';
export const  SEARCH_REQUEST_ERROR = ' SEARCH_REQUEST_ERROR';
